CREATE TABLE dept_emp (
        emp_no INT,
        dept_no STRING)
  ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INPATH '${DEPT_EMP_DATA}' OVERWRITE INTO TABLE dept_emp;
SELECT COUNT(*) FROM dept_emp;
